---
- hosts: builder
  become: true
  
  tasks:

      - name: install software on build server
        package: 
          name: 
            - git
            - maven
            - default-jdk
          state: present 
          cache_valid_time: 3600

      - name: build an artifact
        shell: |
          git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
          cd boxfuse-sample-java-war-hello
          mvn clean package
        args:
          creates: /home/ubuntu/boxfuse-sample-java-war-hello/target/hello-1.0.war

          
- hosts: web
  become: true

  tasks:

      - name: install needed packages
        apt: 
          name:
            - wget
            - default-jdk
            - tomcat9
          state: present
          cache_valid_time: 3600

      - name: download an artifact from build server
        ansible.posix.synchronize:
          src: "/home/ubuntu/boxfuse-sample-java-war-hello/target/hello-1.0.war"
          dest: "/usr/share/tomcat9-root/default_root"
        delegate_to: 3.129.21.136